# Generated by Django 3.0.6 on 2020-06-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='author',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='created_date',
            new_name='published_date',
        ),
    ]
